#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Backing up $app..."

ynh_backup "$install_dir"
ynh_backup "$data_dir"

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/logrotate.d/$app"

ynh_script_progression "Backup of $app completed!"
