#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Backing up Decypharr..."

# Binary
ynh_backup "$install_dir"

# Config and runtime data (config.json, arr state, etc.)
ynh_backup "$data_dir"

# System configs
ynh_backup_conf_nginx
ynh_backup_conf_systemd
ynh_backup_conf_logrotate

ynh_script_progression "Backup of Decypharr completed!"
