#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

ynh_systemctl --service="$app" --action="stop"
yunohost service remove "$app"

#=================================================
# UNMOUNT IF NEEDED
#=================================================
ynh_script_progression "Unmounting filesystems (if any)..."

if mountpoint -q "/mnt/decypharr" 2>/dev/null; then
    fusermount -uz "/mnt/decypharr" || umount -l "/mnt/decypharr" || true
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations..."

ynh_config_remove_logrotate
ynh_config_remove_systemd
ynh_config_remove_nginx

#=================================================
# REMOVE LEFTOVER FILES
#=================================================
ynh_safe_rm "/mnt/decypharr"

ynh_script_progression "Removal of Decypharr completed!"
