#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Restoring Decypharr..."

ynh_restore "$install_dir"
ynh_restore "$data_dir"

ynh_restore_conf_nginx
ynh_restore_conf_systemd
ynh_restore_conf_logrotate

yunohost service add "$app" \
    --description="Debrid blackhole client" \
    --log="/var/log/$app/$app.log"

ynh_systemctl --service="$app" --action="start" --wait_until="listening on"

ynh_script_progression "Restoration of Decypharr completed!"
