#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SERVICE
#=================================================
ynh_script_progression --message="Stopping Decypharr service for upgrade..."

ynh_systemd_action --service_name="$app" --action="stop"

#=================================================
# UPGRADE THE BINARY
#=================================================
ynh_script_progression --message="Upgrading Decypharr binary..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chmod +x "$install_dir/decypharr"

#=================================================
# UPDATE SYSTEM CONFIGS
#=================================================
ynh_script_progression --message="Updating system configurations..."

ynh_add_nginx_config
ynh_add_systemd_config
ynh_use_logrotate

yunohost service add "$app" \
    --description="Debrid blackhole client" \
    --log="/var/log/$app/$app.log"

# NOTE: config.json is NOT re-rendered on upgrade to preserve user settings

#=================================================
# START SERVICE
#=================================================
ynh_script_progression --message="Restarting Decypharr service..."

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

ynh_script_progression --message="Upgrade of $app completed!" --last
